name: flutter_bargraph_example
description: Flutter simple example, single value bar graph viewer with indicators
version: 1.1.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  flutter_bargraph:
    path: ../

flutter:
  uses-material-design: true