name: flutter_bargraph
description: Bar Graph Indicator for Flutter. It graphically displays the current value on a bar graph with animation when the value changes. orientation/direction of the bar is castumizable.
version: 1.2.0
homepage: https://github.com/rickypid/flutter_bargraph
repository: https://github.com/rickypid/flutter_bargraph
issue_tracker: https://github.com/rickypid/flutter_bargraph/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

flutter: