name: flutter_bargraph
description: Bar Graph Indicator for Flutter. It graphically displays the current value on a bar graph with animation when the value changes. orientation/direction of the bar is castumizable.
version: 1.1.0
homepage: https://github.com/rickypid/flutter_bargraph
repository: https://github.com/rickypid/flutter_bargraph
issue_tracker: https://github.com/rickypid/flutter_bargraph/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
